name: libsurrealdb
description: SurrealDB binding
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^7.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: dev.bysensa.surrealdb
        pluginClass: SurrealdbPlugin
      ios:
        pluginClass: SurrealdbPlugin
      macos:
        pluginClass: SurrealdbPlugin


ffigen:
  output: lib/bindings.dart
  headers:
    entry-points:
      - target/libsurrealdb.h
  name: SurrealBindings
  description: Dart bindings to call libsurrealdb functions